version: "3.3"

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - 8080:80
        depends_on:
            - app
        container_name: InfoCoin-nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        container_name: InfoCoin-app

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: InfoCoin
        volumes:
            - ./postgres_data:/var/lib/postgresql/data/
        container_name: InfoCoin-db

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: test@mail.ru
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - 5050:80
